import js from "@eslint/js";
import tseslint from "typescript-eslint";
import reactXPlugin from "eslint-plugin-react-x";
import reactHooksPlugin from "eslint-plugin-react-hooks";
import reactRefreshPlugin from "eslint-plugin-react-refresh";
import jsxA11yPlugin from "eslint-plugin-jsx-a11y";
import sonarjsPlugin from "eslint-plugin-sonarjs";
import unicornPlugin from "eslint-plugin-unicorn";
import importXPlugin from "eslint-plugin-import-x";
import globals from "globals";
import prettierConfig from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "dist/",
      "node_modules/",
      "app/routeTree.gen.ts", // auto-generated by TanStack Router
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,

  // React X (ESLint 9 flat config compatible)
  reactXPlugin.configs["recommended-typescript"],

  {
    files: ["**/*.{ts,tsx}"],
    plugins: {
      "react-hooks": reactHooksPlugin,
      "react-refresh": reactRefreshPlugin,
      "jsx-a11y": jsxA11yPlugin,
      sonarjs: sonarjsPlugin,
      unicorn: unicornPlugin,
      "import-x": importXPlugin,
    },
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    settings: {
      "import-x/resolver-next": [importXPlugin.createNodeResolver()],
    },
    rules: {
      // React Hooks
      ...reactHooksPlugin.configs.recommended.rules,

      // React Refresh
      "react-refresh/only-export-components": [
        "warn",
        { allowConstantExport: true, extraHOCs: ["createFileRoute"] },
      ],

      // JSX A11y
      ...jsxA11yPlugin.configs.recommended.rules,
      "jsx-a11y/no-autofocus": "off",

      // SonarJS
      ...sonarjsPlugin.configs.recommended.rules,

      // Unicorn (selective)
      "unicorn/filename-case": [
        "error",
        { cases: { kebabCase: true, pascalCase: true } },
      ],
      "unicorn/no-array-for-each": "error",
      "unicorn/prefer-node-protocol": "error",
      "unicorn/no-useless-undefined": "error",
      "unicorn/prefer-string-replace-all": "error",
      "unicorn/prefer-ternary": "warn",
      "unicorn/no-negated-condition": "warn",

      // Import X
      "import-x/no-duplicates": "error",
      "import-x/no-cycle": "warn",
      "import-x/order": [
        "error",
        {
          groups: [
            "builtin",
            "external",
            "internal",
            "parent",
            "sibling",
            "index",
          ],
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
    },
  },

  // Relax generated/ui component files
  {
    files: ["app/components/ui/**/*.tsx"],
    rules: {
      "sonarjs/prefer-read-only-props": "off",
      "react-refresh/only-export-components": "off",
    },
  },

  prettierConfig,
);
